### ISSUE TITLE
Update define.xml

### ISSUE THREAD

**Issue by kaz462** [RConsortium/submissions-pilot3-adam#10]
Current define.xml need further processing, issues I found so far:
1. all variables' origin="Derived", e.g., need update to "Predecessor" when a variable is directly from other datasets.
2. ADAS in define.xml: the last column is populated as "LB.VISITNUM" for most of the variables.

**Comment by kaz462** [comment]
3. not able to read in the current define.xml through metacore::define_to_metacore() - it's because the valuelevel part is blank

Sec 2.3 in Pilot 1 [TDF_ADaM_ReadMe](https://github.com/RConsortium/submissions-pilot1/blob/main/adam/TDF_ADaM_ReadMe.docx):
* Explains there is missing information in define.xml, it might not impact the previous pilot submissions, but will impact pilot3 if we want use metacore/metatools;
* It also mentioned "This define.xml document has been created using the ‘Generate Define’ feature of the Pinnacle 21 Community edition from an Excel specification document. " - can someone share the Excel spec? it needs some updates

**Comment by thomas-neitmann** [comment]
> It also mentioned "This define.xml document has been created using the ‘Generate Define’ feature of the Pinnacle 21 Community edition from an Excel specification document. " - can someone share the Excel spec? it needs some updates

@elong0527 @mstackhouse @wangh107 @pkwu55 @howardbaek @lengning As you've worked on the original pilot 1 does either of you know where to find the original Excel specification document?

**Comment by kaz462** [comment]
It seems the define.xml and Excel spec are convertible to each other through P21. but still want to check -
* Is there a spec available that contains the derivation text for ADADAS (ADAS- COG data)?
* Should the programmer draft the spec for ADADAS and update the define.xml? or could the Test Data Factory (TDF) Project Team update for us? 

Thank you!

**Comment by SHAESEN2** [comment]
Thank you for initiating this. I saw some update for ADTTE as well that is required. I would like to see the derivation of the censoring events better explained (when subject dies, the death date is prioritized rather than the discontinuation date).

**Comment by kaz462** [comment]
> * Is there a spec available that contains the derivation text for ADADAS (ADAS- COG data)?

The [define.pdf ](https://github.com/cdisc-org/sdtm-adam-pilot-project/blob/master/updated-pilot-submission-package/900172/m5/53-clin-stud-rep/535-rep-effic-safety-stud/5351-stud-rep-contr/cdiscpilot01/cdiscpilot01.pdf) @laxamanaj  found has the derivation text I was looking for, but further updates are still needed.

**Comment by yutong1307** [comment]
I think the derivation for variable CUMDOSE in ADSL need to be updated as well: derivation describes scenarios for ARMN = 0, 1, 2 but ARMN takes values of 0, 54 and 81

**Comment by laxamanaj** [comment]
One proposal to get an updated define.xml is to read in the .xml into P21, export and excel that the team can work on. then once finalized, we can bring it back into to P21 to re-export a new define.xml.

**Comment by thomas-neitmann** [comment]
> One proposal to get an updated define.xml is to read in the .xml into P21, export and excel that the team can work on. then once finalized, we can bring it back into to P21 to re-export a new define.xml.

Can anyone with access to P21 take this as an action item?

**Comment by laxamanaj** [comment]
Hi, everyone.

I was able to download the CDISCPILOT01 define.xml and re-export it as a spreadsheet through P21.  I've now made it into a google sheet so that all of us may edit as needed. 
https://docs.google.com/spreadsheets/d/1CNtuvaUvVCpqQJU4xc8foXBh1FqRl0fHhsxuVbfIhms/edit#gid=954091763&range=B1 

Per the team roster list, you should all have access per the emails you provided. If not, please submit a request for access. Thanks.

NOTE1 (Action) : I created a new tab called `Pilot3TeamUpdates` where for those who need to make updates to the define should record their updates here.  There is an example on how to enter.

NOTE2 (FYI) : When reading in the CDISCPILOT01 define.xml in P21, I noticed there were over 1000 issues.  
![image](https://user-images.githubusercontent.com/95468392/206357586-618afe57-0b87-421a-a62d-a5a569ad97fa.png)
I'm curious if we have the correct define version, though I'm not sure if CDISC even uses P21 as I hear they have their own validation system.  Either way, let's continue forward with this version as to not hold up work.

Let us know if any further questions.

**Comment by elong0527** [comment]
In pilot1, @pkwu55 help us pass the P21 through some modification of define.xml

please refer https://github.com/RConsortium/submissions-wg/issues/29

and the define.xml in the pilot1 submission doc

https://github.com/RConsortium/submissions-pilot1/blob/main/adam/define.xml

As dataset creation is the main goal for pilot 3, we probably need to follow the most recent version of ADaMIG and create define.xml using R in a reproducible approach.

**Comment by elong0527** [comment]
@wangben718, as you are in pilot3 team, please check if you can find the pilot1 P21 report in Merck internal system and help team clarify questions if any.

**Comment by laxamanaj** [comment]
Thank you, @elong0527 .

As this Pilot3 repo actually forked the Pilot 1 repo after its completion, I was actually able to find the define.xml here (which is what I used to convert to spreadsheet format), 
https://github.com/RConsortium/submissions-pilot3-adam/blob/main/adam/define.xml
which I believe is the one the Pilot 1 team used, based off of the updates from the TDF team into Pilot 1.

This report seems to explain some of the missing data.  Is this the 
P21 report : https://github.com/RConsortium/submissions-pilot3-adam/blob/main/adam/pinnacle21-report-TDF_ADaM.xlsx
and 
TDF explanations  :" https://github.com/RConsortium/submissions-pilot3-adam/blob/main/adam/TDF_ADaM_ReadMe.docx
that was used in Pilot 1?

**Comment by elong0527** [comment]
If they are directly from Pilot 1, yes. 

I would suggest to only use them as reference. The ADaM and Medea version are old. Better to implement following recent version of ADaM IG, that might be a reason if you run P21 that cross check issues per recent ADaM version.

similarly, you may want to up-versioning SDTM, worth to check the minimal version that is acceptable by FDA. 

SDTM: SDTM-3.1.2
ADaM: ADaM-1.0
Medra: 8.0

Potential P21 engine: P21 2010.1

**Comment by laxamanaj** [comment]
Hello Pilot 3 Team.

I did more searching in the TDF repo regarding the define that we're using in Pilot 3 (and maybe what the admiral hackathon is using).

I believe that I may have found more up-to-date specs in this area : https://github.com/phuse-org/TestDataFactory/tree/main/Updated 
In this folder, you'll see the read.me describing the updates they made and also the updated SpecADaM_define20.xlsx file.

I've already converted it to a google spreadsheet.  https://docs.google.com/spreadsheets/d/1H8llhwHSzAz9evPm4wydOr_UQdYhS36DqYZLRTjnQH8/edit?usp=sharing 

For instance you'll see here that ADLBC.CHG is now correctly defined as AVAL-BASE and NOT LB.LBSTNRHI.  Let's all please check our programs are now following these new found specs.

**Comment by zhaol30** [comment]
@laxamanaj Hi Joel, I'll test the package in P21 tomorrow with the eSub team. I'm a little confused from the previous message. Which gsheet spec I should use for testing purpose? Thanks!

**Comment by laxamanaj** [comment]
> @laxamanaj Hi Joel, I'll test the package in P21 tomorrow with the eSub team. I'm a little confused from the previous message. Which gsheet spec I should use for testing purpose? Thanks!

Hi, @zhaol30 . Sorry for missing this question.  Reply now in #61.

**Comment by laxamanaj** [comment]
Define updates : 

Thank you @zhaol30 for helping update the define.  In the current import we have 19 issues : 
![image](https://user-images.githubusercontent.com/95468392/225419660-f773f693-7a90-48a2-936c-a730608c1523.png)

1. @zhaol30 has removed all unncessary datasets and their corresponding variables, codelists, value level info., etc.. , which we are not using in Pilot 3.
2. In Data Type column, some values were input as all CAPS, where Pinnacle 21 was expecting lower case (e.g. 'integer' instead of 'INTEGER').
3. Updated inconsistent origin for USUBJID.  Should now all be 'Predecessor' where ADSL.USUBJID is set from DM.USUBJID, where all other datasets are set from ADSL.USUBJID. Like so : 
![image](https://user-images.githubusercontent.com/95468392/225417679-726c38ea-c50a-4775-b3d2-6a3b6d0df80f.png)
I also removed USUBJID from 'Methods' tab, since it no longer considered a Derivation.
4. Y_BLANK codelist needed the NCI code input, so I included C66742.
5. ADADAS.AVAL also had inconsistent origin, 'Predecessor' vs 'Derived'. Though most of the analysis values are indeed coming directly from QS.QSSTRESN where QSTESTCD=PARAMCD, the newly derived PARAMCD 'ACTOT' technically means that the variable ADADAS.AVAL should now also be considered 'Derived' even though the derivation was only in one PARAMCD. So ADADAS.AVAL is now included in the 'Methods' tab. Following this guidance : 
![image](https://user-images.githubusercontent.com/95468392/225418846-4f34a8a2-c4f8-4cd8-b83d-f8ad46a208da.png)
6. We also removed PARAMTYP, SHIFT, SHIFTN, YNN from codelist tab, since they weren't being referenced by any of the variables in our Pilot 3 datasets.

I am now down to 4 issues in the define check only.  
![image](https://user-images.githubusercontent.com/95468392/225442568-769b194e-171a-4886-902a-1925685cc267.png)

Once fixed I can validate against the .xpt datasets.

**Comment by laxamanaj** [comment]
Update from today's meeting.  Define now has 0 issues and Validation against .xpt datasets now only show 2 issues, where one will be resolved once ADRG is ready and the other issue we have an explanation for and can leave as-is.


These specs are now in branch 10 and will request a PR soon.
![image](https://user-images.githubusercontent.com/95468392/226063630-43fa5c1c-1467-4555-8452-894c998d0f61.png)
![image](https://user-images.githubusercontent.com/95468392/226063712-a73ac2fa-37d1-444e-bda5-45bb885b40c6.png)

**Comment by laxamanaj** [comment]
Re-opening as we had updates for ADLBC specs.  These are the updated specs.

https://docs.google.com/spreadsheets/d/15b0zLYDB_vlU_JtDtk99HsSTVypVvHlU/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true

**Comment by laxamanaj** [comment]
Re-opening to include #101
