### ISSUE TITLE
Review Lock file and remove unused packages

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#133]
The lock file is needed to help build the website, but these packages are not necessary for the submission.

We should identify a way to differentiate between what is needed for the submission and what is needed for the website in this repo

**Comment by robertdevine** [comment]
The reproducible environments (renv) GH workflow can be used to differentiate what is needed for the submission and what is needed for the website.  The Pilot3 website is powered by pkgdown v2.07 so we should be able to differentiate with automation using the six functions wrapped [here](https://pkgdown.r-lib.org/reference/build_site.html). thx.

**Comment by robertdevine** [comment]
This approach of a slight modification to the ADRG appears to also address this [issue](https://github.com/RConsortium/submissions-pilot3-utilities/issues/11) as well. 

No warnings are issued when pilot3 and/or pilot3utils get installed using a slight modification to
the ADRG Section 3 steps.

So far in testing, the list below captures as unused and can be removed using a new snapshot. 
Not certain at that point - later this week is a possibility. thx.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/24f9988f-70ad-451c-b83b-6ac5c2f7ecb4)

**Comment by robertdevine** [comment]
Using the Pilot3 ADRG and following the installation steps through p25 using the pilot3 repository 'main', below are the minimal recursive package dependencies for the pilot3 pkgdown website. The ones in bold are also recursive dependencies for pilot3 and pilot3utils.

**_pilot3 pkgdown website_**:
[1] "**R6**"          "askpass"     "base64enc"   "brio"        "bslib"      
 [6] "cachem"      "callr"       "**cli**"         "**cpp11**"       "curl"       
[11] "desc"        "digest"      "downlit"     "ellipsis"    "evaluate"   
[16] "**fansi**"       "fastmap"     "fs"          "**glue**"        "highr"      
[21] "htmltools"   "httr"        "jquerylib"   "jsonlite"    "knitr"      
[26] "lifecycle"   "**magrittr**"    "memoise"     "mime"        "openssl"    
[31] "**pillar**"      "**pkgconfig**"   "processx"    "ps"          "**purrr**"      
[36] "ragg"        "rappdirs"    "**rlang**"       "rmarkdown"   "rprojroot"  
[41] "sass"        "**stringi**"     "**stringr**"     "sys"         "systemfonts"
[46] "textshaping" "**tibble**"      "tinytex"     "**utf8**"        "**vctrs**"      
[51] "whisker"     "**withr**"       "xfun"        "xml2"        "yaml"  

The _pilot1wrappers_ from the earlier pilot is intended for use with a dedicated Rv4.1.2 so not
applicable to the Pilot3 environment (although it remains in the renv.lock with dependencies
shared by other package(s) in the lock file i.e. survival). Trying to capture a minimal state that
runs successfully for both Pilot3 and the website and then snapshot that as the default lock. thx.

**Comment by robertdevine** [comment]
'**_pilot3_**'Package Dependencies [Recursive]
{"R6", "admiraldev", "cli", "cpp11", "dplyr", "emmeans", "estimability", "fansi",
 "generics", "glue", "hms", "lifecycle", "lubridate", "magrittr", "mvtnorm", "numDeriv",
 "pillar", "pilot3utils", "pkgconfig", "purrr", "rlang","stringi", "stringr", "tibble",
 "tidyr", "tidyselect", "timechange", "utf8", "vctrs","withr"}


'_**pilot3utils**_' Package Dependencies [Recursive] 
{"R6","cli", "cpp11", "dplyr","emmeans", "estimability", "fansi","generics", "glue",
 "lifecycle", "magrittr","mvtnorm", "numDeriv", "pillar", "pkgconfig", "purrr",
 "rlang", "stringi", "stringr", "tibble", "tidyr", "tidyselect", "utf8","vctrs", "withr"}


'**_pilot3_**' Website Package Dependencies [Recursive] 
{"R6", "askpass", "base64enc", "brio", "bslib", "cachem", "callr", "cli", "cpp11", "curl",
 "desc", "digest", "downlit", "ellipsis", "evaluate", "fansi","fastmap", "fontawesome",
 "fs", "glue", "highr", "htmltools", "httr", "jquerylib", "jsonlite", "knitr", "lifecycle",
 "magrittr", "memoise", "mime", "openssl", "pillar","pkgconfig", "processx", "ps", "purrr",
 "ragg", "rappdirs", "rlang", "rmarkdown", "sass", "stringi", "stringr","sys", "systemfonts",
 "textshaping", "tibble", "tinytex", "utf8", "vctrs", "whisker", "withr", "xfun", "xml2", "yaml"}

**Comment by robertdevine** [comment]
@laxamanaj, @bms63, @kaz462, - we developed a pilot3 assembly that removes the cited unused packages here and also removes pilot1wrappers with (several) of its package dependencies - not all since pilot3 does share package dependencies for output with pilot1. Testing the pilot3 assembly (with the pared lock file) through the submission ADRG steps If all goes well, a PR will be issued this week with the trimmed renv.lock. [Non-trivial exercise - this item. As noted above 'box' and/or  tidymodels' may prove helpful with package management in future pilots since the WG discussion has also included
use of ai.] Thanks.

**Comment by robertdevine** [comment]
@laxamanaj, @bms63 , @kaz462, @SHAESEN2 - an insightful example that compels great care when removing _pilot1wrappers_ from Pilot3 is the 'adsl.r' program. Removing pilot1wrappers from renv.lock, breaks the 'adsl.r' program [unless library(pilot3utils)] is included in the library section of the program due to the . It's a tricky business and care is required to avoid breaking changes in this case due to adsl.r program dependency on the **format_sitegr1**( ) function. thx.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/3adc0f78-b22f-41fb-af50-17ea0e5103e8)

**Comment by bms63** [comment]
I think we should remove pilot1wrappers if there is a re-submission.  After ADADAS discussion a re-submission is almost 100% going to happen.  But wait to update until there is confirmation after WG meeting tmr.

**Comment by laxamanaj** [comment]
Hi, @robertdevine . Definitely remove pilot1wrappers altogether form pilot 3.  Pilot1wrappers is essentially the package {pilot3utils}.

**Comment by robertdevine** [comment]
Hi @laxamanaj  - will do and issue the PR this week. thx.

**Comment by robertdevine** [comment]
Fast-forwarding to capture all the changes since the work on this issue from February. We'll also confirm the new {pilot3utils} _Installation Instructions_ work correctly after {pilot1wrappers} is fully removed. thx.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/be198207-7770-4bd8-be56-7efe30467a10)

**Comment by robertdevine** [comment]
@laxamanaj , @bms63 - the testing with {pilot1wrappers} removed is a success. Amazingly, if a tester starts with the .txt version of the lock file and then snapshots to install the {pilot3utils} using the updated namespaces and library references from the updated programs - all outputs are successful. Pretty cool validation - the pared lock file developed in this issue matches the .zip archive (notwithstanding the snapshot step with {pilot3utils} install). I'll issue PR in a few minutes with the updated lock - the package tests successfully with exact output results matching last week's _Installation Instructions_ testing - basically, all set on the .zip archive approach. thx. [Pretty cool!] thx again.
