### ISSUE TITLE
Update Website: feedback from FDA from October Meeting

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#139]
Update Website: feedback from FDA from October Meeting

**Comment by robertdevine** [comment]
Capture an update for the Pilot3 website to present Observations, Questions, and General Discussion from the October 2023 Working Group Meeting including feedback from FDA Pilot Review Team. Thank you.

**Comment by robertdevine** [comment]
@bms63 and @laxamanaj, by way of observation, an interesting experiment: git clone Pilot3 repo and 
lint the entire repository, the expectation given the .lintr configuration is the check should pass. The
 'main' branch does not PASS lint check. What is interesting the header comments do not get flagged 
by the lint check. It is the commented-out code found in single source file: ...wait for it.......

.......report-tlf-pilot3.Rmd. 

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/5925bcf7-71d3-4085-be77-fef6ca822a4e)

If we wrap just the code section with lines 39-40 then the lint results reflect the change.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/cb5de07f-b74d-42cb-967e-92f3da83f74f)

If we wrap both code sections and remove the trailing space on line 28 of the file, the repo passes lint in main.

So, in summary, using exclude to start lint after the widest header doesn't resolve the GH lint check for the Pilot3 
website. What does resolve  the issue is using the #no lint start and #no lint stop for commented out code sections
in the report-tlf-pilot3.Rmd source file. 

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/c6907aeb-ab6b-4818-9a5f-47b2176244d1)

Which do you prefer to resolve the lint check fail: (i)using #no lint start and #no lint stop on the offending source file
sections or (ii)remove the commented-out sections of code from report-tlf-pilot3.Rmd. Option (ii) seems more 
appropriate, but please advise as to course (i) or (ii) for the PR. [Please lmk, PR will get updated with changes 
to get through lintr check and the menu item and home page section description tomorrow.]  Thx.

**Comment by bms63** [comment]
I would prefer to always remove commented out code - unless it is needed to help the reviewers.  I don't think those lines would help the reviwers - it looks like stuff from Posit Cloud anyways
