### ISSUE TITLE
Explore impacts of minor differences between CDISCPilot vs Pilot 3 ADaMs

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#149]
We received this feedback from the FDA. Draft a response on the differences between the  CDISCPilot vs Pilot 3 ADaMs based on these 3 minor differences.
![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/95468392/2edbcce5-6a29-41e0-b59a-800d584a9ac4)

**Comment by SHAESEN2** [comment]
The differences in attributes are all explained in QC findings. I think it might be helpful to include this document in the ADRG.
Any difference in attributes are because pilot 3 ensures that datasets are labelled properly and that there is traceability and transparency. There are none that impact the results.
I did not find differences between types (integer vs double). The impact on a discrepancy such as this will be in the accuracy of the results when a double is defined as integer.
I also did not see any discrepancies between NA vs NULL. Important to note is that NA is special in the sense that it allows observations to be ignored during calculations (na.rm = TRUE). Also missing values are removed automatically in my experience.

**Comment by SHAESEN2** [comment]
library(arsenal)
library(diffdf)
library(waldo)

path <- list(sdtm = "~/submissions-pilot3-adam/submission/sdtm",
             adam = "~/submissions-pilot3-adam/submission/adam",
             cdisc = "~/submissions-pilot3-adam/adam")

### adsl
  adsl <- read_xpt(file.path(path$adam, "adsl.xpt"))
  adsl_cdisc <- read_xpt(file.path(path$cdisc, "adsl.xpt"))

  arsenal::comparedf(adsl, adsl_cdisc)
  diffdf::diffdf(adsl, adsl_cdisc, keys = c("STUDYID", "USUBJID"))
  waldo::compare(adsl,
                 x_arg = "old",
                 adsl_cdisc,
                 y_arg = "new")
  
 # Documented in QC findings: BMIBLGR1  CDISCPILOT01  01-702-1082          <25   
 
### adtte
  adtte <- read_xpt(file.path(path$adam, "adtte.xpt"))
  adtte_cdisc <- read_xpt(file.path(path$cdisc, "adtte.xpt"))

  arsenal::comparedf(adtte, adtte_cdisc)
  diffdf::diffdf(adtte, adtte_cdisc, keys = c("STUDYID", "USUBJID"))
  waldo::compare(adtte,
                 x_arg = "old",
                 adtte_cdisc,
                 y_arg = "new")
  
  # Attributes don't impact on the analysis 

### adae
  adae <- read_xpt(file.path(path$adam, "adae.xpt"))
  adae_cdisc <- read_xpt(file.path(path$cdisc, "adae.xpt"))
  
  arsenal::comparedf(adae, adae_cdisc)
  diffdf::diffdf(adae, adae_cdisc, keys = c("STUDYID", "USUBJID", "AESEQ"))
  waldo::compare(adae,
                 x_arg = "old",
                 adae_cdisc,
                 y_arg = "new")

  # Differences are documented in QC findings
  # Attributes don't impact on the analysis
  
### adlb
  adlbc <- read_xpt(file.path(path$adam, "adlbc.xpt"))
  adlbc_cdisc <- read_xpt(file.path(path$cdisc, "adlbc.xpt"))
  
  arsenal::comparedf(adlbc, adlbc_cdisc)
  diffdf::diffdf(adlbc, adlbc_cdisc, keys = c("STUDYID", "USUBJID", "LBSEQ", "PARAMCD", "AVISIT"))
  waldo::compare(adlbc,
                 x_arg = "old",
                 adlbc_cdisc,
                 y_arg = "new")
  
  # Attributes don't impact on the analysis

### adadas
  adadas <- read_xpt(file.path(path$adam, "adadas.xpt"))
  adadas_cdisc <- read_xpt(file.path(path$cdisc, "adadas.xpt"))

  arsenal::comparedf(adadas, adadas_cdisc)
  diffdf::diffdf(adadas, adadas_cdisc, keys = c("STUDYID", "USUBJID", "QSSEQ", "PARAMCD", "AVISIT"))
  waldo::compare(adadas,
                 x_arg = "old",
                 adadas_cdisc,
                 y_arg = "new")
