### ISSUE TITLE
Ben's Findings: Remove duplicated image, re-run pdf

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#170]
Hi @laxamanaj 

Just to keep the repo as clean as possible.  Can we remove this duplicated image from the folder?

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/b0eec637-2160-45ee-ab2f-a09ef441f662)

**Comment by laxamanaj** [comment]
Hi, @bms63 .  Thanks for cleaing this up.  Yes, I wanted to remove the `adrg_images` folder.  By default when adding images in quarto visual editor, it created an `images` folder automatically.  Since that seemed to be the standard behavior, I think it's best to keep all images in the `images` folder and remove `adrg_images`.
