### ISSUE TITLE
Program ADLBC

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#3]

**Comment by DadongZ** [comment]
Hi @thomas-neitmann I would like to be one of members on this issue. Thanks

**Comment by thomas-neitmann** [comment]
Great, please assign yourself on the right @DadongZ!

**Comment by SHAESEN2** [comment]
I did not see any branch created. Is anyone already started on this?

**Comment by DadongZ** [comment]
@SHAESEN2 I just made a push with branch name "3_adlb"

**Comment by DadongZ** [comment]
@thomas-neitmann Could you grant me access the https://rstudio.cloud/spaces/302021/content ? I am currently using my local computer environment.

**Comment by thomas-neitmann** [comment]
@DadongZ Just re-sent the invite to join via mail and pasted the link in a DM on Slack.

**Comment by DadongZ** [comment]
@thomas-neitmann Thanks

**Comment by SHAESEN2** [comment]
@DadongZ I also pushed a branch with an early draft. Perhaps we can merge them and continue from there. It is whatever you want to do :) Enjoy. I might have some again next week to help.

**Comment by nicolekjones** [comment]
@DadongZ one update from meeting today: we will be only programming ADLBC because that is all that is needed for the input for TLGs

**Comment by nicolekjones** [comment]
@SHAESEN2 thanks for this draft! which ADLB were you programming?

**Comment by DadongZ** [comment]
> @DadongZ one update from meeting today: we will be only programming ADLBC because that is all that is needed for the input for TLGs

Thanks for the update @nicolekjones It's interesting my calendar showed the pilot3 meeting is at 12pm EST today.

**Comment by SHAESEN2** [comment]
Issues in define:
- In code list LNH is says LAVAL, but they mean AVAL

**Comment by SHAESEN2** [comment]
@DadongZ @nicolekjones I did not see any progress yet, so I merged my branch #34. Not much progress was added since last time.

**Comment by DadongZ** [comment]
@SHAESEN2 Thanks for the updates. I will be working on it today or tomorrow. @nicolekjones

**Comment by nicolekjones** [comment]
@SHAESEN2  @DadongZ  I'll be working on this during the afternoon today. Thanks for your work @SHAESEN2 !

**Comment by DadongZ** [comment]
@SHAESEN2 @nicolekjones Are you guys working on the R cloud? I am trying to switch from my working computer to the cloud but seems getting a few env issues.

**Comment by SHAESEN2** [comment]
Any update on the progress?

**Comment by SHAESEN2** [comment]
> Any update on the progress?

I think all variables are now programmed. I'm not sure if they are correct. perhaps someone else can do QC and add labels?

**Comment by DadongZ** [comment]
@SHAESEN2 Thank you for your hard work. I will be working on it this week.

**Comment by DadongZ** [comment]
@SHAESEN2 @nicolekjones I had some minors edits for your review and added labels for intermediate datasets until `adlb05`. Not sure why the labels haven't been preserved in `adlb06/07`. I will continue to work on it. Nice work @SHAESEN2 
Key changes made:
1. Excluded envsetup::() functions. My thought is that envsetup isn't an official package and may lead some concern to be included in a submission.
2. Added some comments/documentations
3. Involved a new package labelled::() for labeling.

**Comment by SHAESEN2** [comment]
> 1. Excluded envsetup::() functions. My thought is that envsetup isn't an official package and may lead some concern to be included in a submission.
envsetup is part of the pharmaverse, so it is official :). It works similar to libnames in SAS and is mainly used for development purposes.

**Comment by nicolekjones** [comment]
Hi @DadongZ and @SHAESEN2, reviewed the pgm and had a few comments/made some edits in my recent commit: 

1. some of the labels don't match what should be in the output dataset; wasn't sure if there was a reason for this so I just made a comment and left it
2. slight adjustment needed when creating AVALC
3. changed PARCAT1 from Chemistry to CHEM to match final dataset
4. when creating baseline values, I think it's better to use LBBLFL for filtering
5. When merging baseline values back in, LBSEQ shouldn't be used so that all observations have BASE populated
6. Made some adjustments when creating AVISIT and AVISITN
7. Cleaned up the final dataset (adlb08) to only include the expected variables
8. Lastly, we appear to be missing a few observations in our final dataset in our dataset and the original adlbc [you can use `summary(arsenal::comparedf(prodc, adlb08))` to investigate]

Hope this all makes sense. Talk tomorrow :)

**Comment by nicolekjones** [comment]
> Hi @DadongZ and @SHAESEN2, reviewed the pgm and had a few comments/made some edits in my recent commit:
> 
> 1. some of the labels don't match what should be in the output dataset; wasn't sure if there was a reason for this so I just made a comment and left it
> 2. slight adjustment needed when creating AVALC
> 3. changed PARCAT1 from Chemistry to CHEM to match final dataset
> 4. when creating baseline values, I think it's better to use LBBLFL for filtering
> 5. When merging baseline values back in, LBSEQ shouldn't be used so that all observations have BASE populated
> 6. Made some adjustments when creating AVISIT and AVISITN
> 7. Cleaned up the final dataset (adlb08) to only include the expected variables
> 8. Lastly, we appear to be missing a few observations in our final dataset in our dataset and the original adlbc [you can use `summary(arsenal::comparedf(prodc, adlb08))` to investigate]
> 
> Hope this all makes sense. Talk tomorrow :)

Also one more comment:

for ANL01F I wasn't 100% sure how we should be defining it.

**Comment by SHAESEN2** [comment]
> Hi @DadongZ and @SHAESEN2, reviewed the pgm and had a few comments/made some edits in my recent commit:
> 
> 1. some of the labels don't match what should be in the output dataset; wasn't sure if there was a reason for this so I just made a comment and left it
I would adjust the labels in the end to ensure they match with the production dataset. Adding labels in between makes it more difficult and avoids that you need to use exotic packages such as sjmisc. You can check how it is done for ADSL.

> 2. slight adjustment needed when creating AVALC
OK

> 3. changed PARCAT1 from Chemistry to CHEM to match final dataset
OK

> 4. when creating baseline values, I think it's better to use LBBLFL for filtering
As long as it matches the production dataset it is OK. However, it is safer to derive baseline rather than rely on SDTM.

> 5. When merging baseline values back in, LBSEQ shouldn't be used so that all observations have BASE populated
Indeed.

> 6. Made some adjustments when creating AVISIT and AVISITN
Looks great

> 7. Cleaned up the final dataset (adlb08) to only include the expected variables
Great

> 8. Lastly, we appear to be missing a few observations in our final dataset in our dataset and the original adlbc [you can use `summary(arsenal::comparedf(prodc, adlb08))` to investigate]
Can you list a few?

> 
> Hope this all makes sense. Talk tomorrow :)

For ANL01FL:
https://github.com/phuse-org/phuse-scripts/blob/master/data/adam/cdisc/define.xml
"Y if this ALBTRVAL is the largest for the subject in Visits 4-12 inclusive, null otherwise (if this value of ALBTRVAL occurs more than once, the first one is flagged)

**Comment by DadongZ** [comment]
> > 1. Excluded envsetup::() functions. My thought is that envsetup isn't an official package and may lead some concern to be included in a submission.
> >    envsetup is part of the pharmaverse, so it is official :). It works similar to libnames in SAS and is mainly used for development purposes.

Thanks @SHAESEN2. Great to know that :)
