### ISSUE TITLE
Call to R Consortium Review Pilot 3 Proposal

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#37]
Hello R Consortium.

Here is the link to the current draft of the [Pilot 3 Proposal](https://github.com/RConsortium/submissions-pilot3-adam/blob/main/vignettes/fda/R_Submission_Pilot_3_ADaM_FDA_Execution_Proposal_02Dec2022.pdf).

Please review at your earliest convenience before 13JAN2023.  Per your review, feel free to leave comments, feedback or any questions you may have in this issue.  Many thanks for taking the time to review.

Best,
@thomas-neitmann & @laxamanaj

**Comment by SHAESEN2** [comment]
I would like to propose a slight change of scope. Instead of letting the reviewers install a package “pilot3wrappers” to let the scripts run, we could use a more traditional workflow.
- submit the functions as one txt file using pkglite
- submit the programs as one txt file using pkglite

This approach is perfectly feasible and compatible with complex computing environments considering:
- some computing environments are not foreseen to create and build R packages
- it avoids that all lead/senior programmers need to be trained in package development and debugging
- more aligned with traditional workflows eg folder structures within computing environments, no need for additional subfolders, ...
- easier to reconstruct the delivery by sourcing the folder that is created by unpacking the functions.txt file

**Comment by nanxstats** [comment]
Nice. The RStudio IDE download link should be updated to <https://posit.co/download/rstudio-desktop/>.

The other thing is, all the technical details should be included in ADRG instead of the cover letter?

**Comment by robertdevine** [comment]
Thank you @SHAESEN2.  

@thomas-neitmann and @laxamanaj, please raise @SHAESEN2 's proposal at the January 2023 R Consortium general meeting. [If the proposed change in scope is accepted, please consider me a voluntary tester across the OS groupings.] Thank you.

**Comment by bms63** [comment]
Is this being created in Rmarkdown?

**Comment by bms63** [comment]
I think I am confused.  

Are we building a package that then can be run locally at the FDA after submitting through the etcd portal?  Like they can install it and then they can rerun the analysis?

**Comment by robertdevine** [comment]
@bms63 Review of the [Pilot 2 ADRG](https://github.com/RConsortium/submissions-pilot2-to-fda/blob/main/m5/datasets/rconsortiumpilot2/analysis/adam/datasets/adrg.pdf) Appendices (1,2) may provide additional clarity and detail regarding your query. Thank you.

**Comment by SHAESEN2** [comment]
![image](https://user-images.githubusercontent.com/47894155/212852182-42031a71-4fde-46ea-8c45-64eb75a37576.png)

**Comment by nanxstats** [comment]
While I understand the concept, I respectfully disagree with Steven's proposal of using a collection of unstructured R scripts instead of a standard R package structure validated by pilot 1 and pilot 2 submissions.

An R package-based workflow offers advantages in reusability, documentation, testing, versioning, namespacing, dependency management, collaboration, among many others. Most importantly, it offers a standard engineering workflow that everyone in the industry can follow. The proposal above also involves an off-label use of pkglite, which I would not personally encourage.

I acknowledge that some individuals within organizations may not have experience writing R packages. However, this is an issue that should be addressed at the organizational level. Our focus in the submission working group should be on promoting industry-standard best practices and frameworks that align with the open- source community.

cc @joseph-rickert @lengning

**Comment by laxamanaj** [comment]
> 

Hi, @nanxstats .  Many thanks for reviewing.

I will update the link in this proposal.

As for the technical details, you are right, these would eventually go into the final ADRG.  Though for this document, this is actually a proposal, not a cover letter, which the FDA asked us to write the details on how we expect the FDA staff to receive our package and execute.

Best,
Joel

**Comment by laxamanaj** [comment]
Updates to cover letter and adrg will describe final steps to prepare submission.
