### ISSUE TITLE
Create vignettes for Datasets like Pilot1 did for Tables

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#59]
![image](https://user-images.githubusercontent.com/10111024/218189630-8273ce47-3e78-4325-be25-1c035593b270.png)

**Comment by laxamanaj** [comment]
- [ ] Initiation of packages

- [ ] Read in SDTM data

- [ ] ADaM derivations

- [ ] Export to .xpt and do a head() to show the first 6 obs of the ADaM data

- [ ] qc_*.R scripts to show the diffdf() summary

- [ ] render the QC findings we have here to support why we expect the differences in step 5? https://github.com/RConsortium/submissions-pilot3-adam/wiki/QC-Findings

**Comment by thomas-neitmann** [comment]
Do we really want to create vignettes for the individual scripts? I don't think this adds much value compared to the code you can already take a look at on GitHub. Plus now we have the same information in two places rather than having just a single source of truth.

**Comment by laxamanaj** [comment]
I think this is a nice-to-have, for the github pilot 3 site when public viewers check the site, similar to pilot 1. But I agree, not needed for our submission purposes.  

Maybe we can keep this on the table for after we submit, as a way to share with the public what we did or within our internal companies.

**Comment by bms63** [comment]
> Do we really want to create vignettes for the individual scripts? I don't think this adds much value compared to the code you can already take a look at on GitHub. Plus now we have the same information in two places rather than having just a single source of truth.

I think it does add value as we can show some of the variables being derived in datatables, comparisons, write up of issues encountered and limitations.  Rather than just the raw R code in the github repo.  But I see your point of we don't need a full rerun of the datasets in the vignette with a step-by-step guide!
 
Talk more at today's meeting, but we can put on the backlog for now and focus on submission.

**Comment by laxamanaj** [comment]
> Thank you, @laxamanaj. To summarize the action steps discussed at the weekly Check-In to address Issue #59 and finalized ADRG. [1]Pilot3 **report-tlf.pdf** (based upon Pilot1) with timestamps [2]Pilot3 **report-adam.pdf** (based on updated Pilot3 QC Findings with finalized ADRG) [3]Pilot3 Website (GH Pages feature) for discussion (limitations, differences from Pilot1, and related)

Thanks again for bringing this up, @robertdevine .  For both reports, of course it will be helpful to create from R-markdown (.RMD) so that we can display in our github website as well.  Please let me know if you need extra support on this as you may ask any of our Pilot 3 members to assist you if needed.

**Comment by laxamanaj** [comment]
Hi, @robertdevine .  Thanks again for meeting me today.  Thank you for your summary of our conversation in slack. I will copy and paste here for our tracking : 

_Thanks 
[@Joel Laxamana](https://pharmaverse.slack.com/team/U0493A50B5K)
, nice catching up. The new Pilot3 structure appears intuitive (and generic) in the sense that business/organizational nuance can be added by each pharma following a fork action - so yes, real value captured and consistent flow across the Pilot1|2|3|[4] series. As discussed just a small referential impact on the `report-tlf.pdf` otherwise no impact (on Issue #59[2] and Issue #59[3]). 
Have a nice holiday weekend. [Talk at next week's Check In Tc]._

Thanks again for helping align with your updates, @robertdevine !

**Comment by robertdevine** [comment]
Hello @laxamanaj, yesterday @pstata organized a mid-week Check-In on Issue #59. [Thank you again, @pstata.] The meeting minutes will get added to Pilot3 'meeting_minutes' in GH later today. [They are in Slack private channel at the moment.]

At yesterday's Check-In we reviewed status on [1], [2], and [3]. @pstata self-assigned completion of the report-tlf.Rmd (i.e. [1]). Just to confirm following the Issue #107 Pilot3 repo updates from last week, for the Issue #59 vignettes [report-tlf and report-adam] the R programs (live under the **~/submission/programs** directory) calling the R Markdown .Rmd files (which live under the **~/vignettes** directory) and write the 'pdf' outputs to the **~/vignettes/pdf** directory.  [There is a **~/submission/output** directory hence the confirmation request to resolve the distinction regarding Pilot3 program pdf output for the Issue #59 vignettes.] We should be able to move this issue from '_In-Progress_' to '_In-Review_' at tomorrow's Check-in. Thanks again.

**Comment by laxamanaj** [comment]
Connected to #119   Can close this for now.
